import sys
from dataclasses import dataclass

import numpy as np 
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, RobustScaler, OrdinalEncoder, TargetEncoder

from src.exception import CustomException
from src.logger import logging
import os

from src.utils import save_object

@dataclass
class DataTransformationConfig:
    # Fixed typo in filename (proprocessor.pkl -> preprocessor.pkl)
    preprocessor_obj_file_path = os.path.join('artifacts', "preprocessor.pkl")

class DataTransformation:
    def __init__(self):
        self.data_transformation_config = DataTransformationConfig()

    def get_data_transformer_object(self):
        '''
        This function is responsible for data transformation
        '''
        try:
            # Set up categorical columns based on requested encodings
            target_encoded_columns = ["sector"]
            ordinal_encoded_columns = ["agePossession"]
            onehot_encoded_columns = ["balcony"]
            
            # Remaining numerical columns (excluding the targets)
            numerical_columns = [
                'area', 'bedRoom', 'bathroom', 'floorNum', 'has_servant_room',
                'has_study_room', 'has_pooja_room', 'has_store_room', 'has_others',
                'furnishing_type', 'luxury_score', 'super_built_up_area',
                'built_up_area', 'carpet_area'
            ]

            num_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="median")),
                    ("scaler", RobustScaler())
                ]
            )

            # Target Encoding on sector (with automatic smoothing)
            target_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("target_encoder", TargetEncoder(target_type="continuous", smooth="auto")),
                    ("scaler", RobustScaler())
                ]
            )

            # Label Encoding equivalent (OrdinalEncoder) for agePossession
            ordinal_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("ordinal_encoder", OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)),
                    ("scaler", RobustScaler())
                ]
            )

            # One-hot encoding on the remaining categorical columns
            cat_pipeline = Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("one_hot_encoder", OneHotEncoder(handle_unknown='ignore')),
                    # Centering is False here to prevent issues with sparse matrices generated by OneHotEncoder
                    ("scaler", RobustScaler(with_centering=False))
                ]
            )

            logging.info(f"Numerical columns: {numerical_columns}")
            logging.info(f"Target Encoded columns: {target_encoded_columns}")
            logging.info(f"Ordinal Encoded columns: {ordinal_encoded_columns}")
            logging.info(f"One-hot Encoded columns: {onehot_encoded_columns}")

            preprocessor = ColumnTransformer(
                [
                    ("num_pipeline", num_pipeline, numerical_columns),
                    ("target_pipeline", target_pipeline, target_encoded_columns),
                    ("ordinal_pipeline", ordinal_pipeline, ordinal_encoded_columns),
                    ("cat_pipeline", cat_pipeline, onehot_encoded_columns)
                ]
            )

            return preprocessor
        
        except Exception as e:
            raise CustomException(e, sys)
        
    def initiate_data_transformation(self, train_path, test_path):
        try:
            train_df = pd.read_csv(train_path)
            test_df = pd.read_csv(test_path)

            logging.info("Read train and test data completed")
            logging.info("Obtaining preprocessing object")

            preprocessing_obj = self.get_data_transformer_object()

            # Multiple target columns separated out
            target_columns = ["price", "price_per_sqft"]
            
            # Segregate features and targets
            input_feature_train_df = train_df.drop(columns=target_columns, axis=1)
            target_feature_train_df = train_df[target_columns]

            input_feature_test_df = test_df.drop(columns=target_columns, axis=1)
            target_feature_test_df = test_df[target_columns]

            logging.info(
                "Applying preprocessing object on training dataframe and testing dataframe."
            )

            # Fit transform on train set. TargetEncoder requires the "y" (price) to calculate encoding.
            input_feature_train_arr = preprocessing_obj.fit_transform(
                input_feature_train_df, 
                target_feature_train_df["price"]
            )
            
            # Transform test set
            input_feature_test_arr = preprocessing_obj.transform(input_feature_test_df)

            # Concatenate preprocessed features with both target features
            train_arr = np.c_[
                input_feature_train_arr, np.array(target_feature_train_df)
            ]
            test_arr = np.c_[
                input_feature_test_arr, np.array(target_feature_test_df)
            ]

            logging.info("Saved preprocessing object.")

            save_object(
                file_path=self.data_transformation_config.preprocessor_obj_file_path,
                obj=preprocessing_obj
            )

            return (
                train_arr,
                test_arr,
                self.data_transformation_config.preprocessor_obj_file_path,
            )
            
        except Exception as e:
            raise CustomException(e, sys)